// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/current_user": {
            "get": {
                "description": "获取当前登录用户的信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "获取当前用户信息",
                "responses": {
                    "200": {
                        "description": "获取用户信息成功",
                        "schema": {
                            "$ref": "#/definitions/routes.currentUserResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "获取用户信息失败",
                        "schema": {
                            "$ref": "#/definitions/routes.currentUserResponseFailed"
                        }
                    }
                }
            }
        },
        "/api/login": {
            "post": {
                "description": "通过邮箱和密码进行用户登录验证",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "$ref": "#/definitions/routes.loginResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "登录失败",
                        "schema": {
                            "$ref": "#/definitions/routes.loginResponseFailed"
                        }
                    }
                }
            }
        },
        "/api/models_list": {
            "get": {
                "description": "获取可用的AI模型列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模型"
                ],
                "summary": "获取模型列表",
                "responses": {
                    "200": {
                        "description": "获取模型列表成功",
                        "schema": {
                            "$ref": "#/definitions/routes.modelsListResponse"
                        }
                    }
                }
            }
        },
        "/api/send_verify_code": {
            "post": {
                "description": "向指定邮箱发送验证码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "发送验证码",
                "parameters": [
                    {
                        "description": "邮箱地址",
                        "name": "email",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.sendVerifyCodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "验证码发送成功",
                        "schema": {
                            "$ref": "#/definitions/routes.sendVerifyCodeResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "验证码发送失败",
                        "schema": {
                            "$ref": "#/definitions/routes.sendVerifyCodeResponseFailed"
                        }
                    }
                }
            }
        },
        "/api/sign": {
            "post": {
                "description": "用户每日签到获取积分",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户签到",
                "responses": {
                    "200": {
                        "description": "签到成功",
                        "schema": {
                            "$ref": "#/definitions/routes.signResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "签到失败",
                        "schema": {
                            "$ref": "#/definitions/routes.signResponseFailed"
                        }
                    }
                }
            }
        },
        "/api/signup": {
            "post": {
                "description": "通过用户名、邮箱、密码和验证码进行用户注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册信息",
                        "name": "signup",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.signupRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "注册成功",
                        "schema": {
                            "$ref": "#/definitions/routes.signupResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "注册失败",
                        "schema": {
                            "$ref": "#/definitions/routes.signupResponseFailed"
                        }
                    }
                }
            }
        },
        "/api/verify_points": {
            "post": {
                "description": "通过订单ID验证并充值积分",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "验证积分充值",
                "parameters": [
                    {
                        "description": "验证信息",
                        "name": "verifyPoints",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.verifyPointsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "积分验证成功",
                        "schema": {
                            "$ref": "#/definitions/routes.verifyPointsResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "积分验证失败",
                        "schema": {
                            "$ref": "#/definitions/routes.verifyPointsResponseFailed"
                        }
                    }
                }
            }
        },
        "/api/verify_vip": {
            "post": {
                "description": "通过订单ID验证并激活VIP会员资格",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "验证VIP会员",
                "parameters": [
                    {
                        "description": "验证信息",
                        "name": "verifyVip",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.verifyVipRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "VIP验证成功",
                        "schema": {
                            "$ref": "#/definitions/routes.verifyVipResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "VIP验证失败",
                        "schema": {
                            "$ref": "#/definitions/routes.verifyVipResponseFailed"
                        }
                    }
                }
            }
        },
        "/chat/conversations_list": {
            "get": {
                "description": "获取当前用户的所有对话列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "获取对话列表",
                "responses": {
                    "200": {
                        "description": "获取对话列表成功",
                        "schema": {
                            "$ref": "#/definitions/routes.conversationsListResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "获取对话列表失败",
                        "schema": {
                            "$ref": "#/definitions/routes.conversationsListResponseFailed"
                        }
                    }
                }
            }
        },
        "/chat/delete_conversation": {
            "post": {
                "description": "删除指定的对话及其相关消息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "删除对话",
                "parameters": [
                    {
                        "description": "删除对话请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.deleteConversationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除对话成功",
                        "schema": {
                            "$ref": "#/definitions/routes.deleteConversationResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "删除对话失败",
                        "schema": {
                            "$ref": "#/definitions/routes.deleteConversationResponseFailed"
                        }
                    }
                }
            }
        },
        "/chat/delete_message": {
            "post": {
                "description": "删除指定的消息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "删除消息",
                "parameters": [
                    {
                        "description": "删除消息请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.deleteMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除消息成功",
                        "schema": {
                            "$ref": "#/definitions/routes.deleteMessageResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "删除消息失败",
                        "schema": {
                            "$ref": "#/definitions/routes.deleteMessageResponseFailed"
                        }
                    }
                }
            }
        },
        "/chat/generate": {
            "post": {
                "description": "根据用户输入生成AI回复，使用SSE流式传输",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "生成AI回复",
                "parameters": [
                    {
                        "description": "生成请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.generateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "流式响应，返回AI生成内容",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "生成失败",
                        "schema": {
                            "$ref": "#/definitions/routes.generateResponseFailed"
                        }
                    }
                }
            }
        },
        "/chat/new_conversation": {
            "get": {
                "description": "为当前用户创建一个新的对话",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "创建新对话",
                "responses": {
                    "200": {
                        "description": "创建新对话成功",
                        "schema": {
                            "$ref": "#/definitions/routes.newConversationResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "创建新对话失败",
                        "schema": {
                            "$ref": "#/definitions/routes.newConversationResponseFailed"
                        }
                    }
                }
            }
        },
        "/chat/share_messages": {
            "post": {
                "description": "将指定的消息ID列表创建为分享链接",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "分享消息",
                "parameters": [
                    {
                        "description": "分享消息请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.shareMessagesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建分享成功",
                        "schema": {
                            "$ref": "#/definitions/routes.shareMessagesResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "创建分享失败",
                        "schema": {
                            "$ref": "#/definitions/routes.shareMessagesResponseFailed"
                        }
                    }
                }
            }
        },
        "/chat/stop": {
            "post": {
                "description": "停止指定对话的AI生成过程",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "停止生成",
                "parameters": [
                    {
                        "description": "停止生成请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.stopRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "停止生成成功",
                        "schema": {
                            "$ref": "#/definitions/routes.stopResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "停止生成失败",
                        "schema": {
                            "$ref": "#/definitions/routes.stopResponseFailed"
                        }
                    }
                }
            }
        },
        "/chat/thread_list": {
            "post": {
                "description": "获取当前用户的线程列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "获取线程列表",
                "responses": {
                    "200": {
                        "description": "获取线程列表成功",
                        "schema": {
                            "$ref": "#/definitions/routes.threadListResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "获取线程列表失败",
                        "schema": {
                            "$ref": "#/definitions/routes.threadListResponseFailed"
                        }
                    }
                }
            }
        },
        "/chat/{shareID}": {
            "get": {
                "description": "根据分享ID获取分享的消息内容",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "获取分享内容",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分享ID",
                        "name": "shareID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取分享内容成功",
                        "schema": {
                            "$ref": "#/definitions/routes.loadShareMessagesResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "获取分享内容失败",
                        "schema": {
                            "$ref": "#/definitions/routes.loadShareMessagesResponseFailed"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "routes.conversationsListResponseFailed": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "routes.conversationsListResponseSuccess": {
            "type": "object",
            "properties": {
                "conversations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/utils.Conversation"
                    }
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "routes.currentUserResponseFailed": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "routes.currentUserResponseSuccess": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "uuid-string"
                },
                "isMember": {
                    "type": "boolean",
                    "example": true
                },
                "memberLevel": {
                    "type": "string",
                    "example": "VIP"
                },
                "points": {
                    "type": "integer",
                    "example": 100
                },
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "username": {
                    "type": "string",
                    "example": "currentuser"
                }
            }
        },
        "routes.deleteConversationRequest": {
            "type": "object",
            "properties": {
                "conversationID": {
                    "type": "string",
                    "example": "uuid-string"
                }
            }
        },
        "routes.deleteConversationResponseFailed": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "routes.deleteConversationResponseSuccess": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "routes.deleteMessageRequest": {
            "type": "object",
            "properties": {
                "messageID": {
                    "type": "string",
                    "example": "uuid-string"
                }
            }
        },
        "routes.deleteMessageResponseFailed": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "routes.deleteMessageResponseSuccess": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "routes.generateRequest": {
            "type": "object",
            "properties": {
                "base64": {
                    "type": "string",
                    "example": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg=="
                },
                "conversationID": {
                    "type": "string",
                    "example": "uuid-string"
                },
                "model": {
                    "type": "string",
                    "example": "gpt-3.5-turbo"
                },
                "prompt": {
                    "type": "string",
                    "example": "你好，帮我写一个Hello World程序"
                }
            }
        },
        "routes.generateResponseFailed": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "routes.loadShareMessagesResponseFailed": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "routes.loadShareMessagesResponseSuccess": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/utils.Message"
                    }
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "routes.loginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "password123"
                }
            }
        },
        "routes.loginResponseFailed": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "用户名或密码错误"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "routes.loginResponseSuccess": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "登录成功"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "routes.modelsListResponse": {
            "type": "object",
            "properties": {
                "models": {
                    "type": "array",
                    "items": {}
                }
            }
        },
        "routes.newConversationResponseFailed": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "routes.newConversationResponseSuccess": {
            "type": "object",
            "properties": {
                "conversationID": {
                    "type": "string",
                    "example": "uuid-string"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "routes.sendVerifyCodeRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                }
            }
        },
        "routes.sendVerifyCodeResponseFailed": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "发送失败"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "routes.sendVerifyCodeResponseSuccess": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "发送成功"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "routes.shareMessagesRequest": {
            "type": "object",
            "properties": {
                "messageIDs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "message-id-1",
                        "message-id-2"
                    ]
                }
            }
        },
        "routes.shareMessagesResponseFailed": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "routes.shareMessagesResponseSuccess": {
            "type": "object",
            "properties": {
                "share_id": {
                    "type": "string",
                    "example": "a1b2c3d4e5f67890"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "routes.signResponseFailed": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "今日已签到"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "routes.signResponseSuccess": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "签到成功"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "routes.signupRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "newuser@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "password123"
                },
                "username": {
                    "type": "string",
                    "example": "newuser"
                },
                "verifyCode": {
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "routes.signupResponseFailed": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "该邮箱已被注册"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "routes.signupResponseSuccess": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "注册成功"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "user": {
                    "$ref": "#/definitions/routes.signupUser"
                }
            }
        },
        "routes.signupUser": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "newuser@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "uuid-string"
                },
                "username": {
                    "type": "string",
                    "example": "newuser"
                }
            }
        },
        "routes.stopRequest": {
            "type": "object",
            "properties": {
                "conversationID": {
                    "type": "string",
                    "example": "uuid-string"
                }
            }
        },
        "routes.stopResponseFailed": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "内部错误"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "routes.stopResponseSuccess": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "routes.threadListResponseFailed": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "routes.threadListResponseSuccess": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "thread_list": {
                    "type": "array",
                    "items": {}
                }
            }
        },
        "routes.verifyPointsRequest": {
            "type": "object",
            "properties": {
                "orderID": {
                    "type": "string",
                    "example": "订单ID"
                }
            }
        },
        "routes.verifyPointsResponseFailed": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "无效 orderID"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "routes.verifyPointsResponseSuccess": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "routes.verifyVipRequest": {
            "type": "object",
            "properties": {
                "force": {
                    "type": "boolean",
                    "example": false
                },
                "orderID": {
                    "type": "string",
                    "example": "订单ID"
                }
            }
        },
        "routes.verifyVipResponseFailed": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "无效 orderID"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "routes.verifyVipResponseSuccess": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "utils.Conversation": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "utils.Message": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "conversationID": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "reasoningContent": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Aurora API",
	Description:      "API文档 for Aurora 项目",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
